# Generated by Django 4.2.16 on 2024-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_short_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
