# Generated by Django 4.2.16 on 2024-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_middle_name_alter_unit_unit_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
