# Generated by Django 4.2.16 on 2024-11-04 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_email_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Student', 'Student'), ('Alumni', 'Alumni'), ('Parent', 'Parent'), ('Guardian', 'Guardian'), ('Supplier', 'Supplier'), ('Service Provider', 'Service Provider'), ('Visitor', 'Visitor')], default='Faculty', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
