# Generated by Django 4.2.16 on 2024-11-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_transaction_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
