# Generated by Django 4.2.16 on 2024-11-05 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_clientsurvey_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
