# Generated by Django 4.2.16 on 2024-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_clientsurvey_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='evaluator',
            field=models.CharField(blank=True, null=True),
        ),
    ]
