# Generated by Django 4.2.16 on 2024-11-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
