# Generated by Django 4.2.16 on 2024-11-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='others',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientsurvey',
            name='client_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Alumni', 'Alumni'), ('Parent/Guardian', 'Parent/Guardian'), ('Supplier/Provider', 'Supplier/Provider'), ('Visitor', 'Visitor')], default='Faculty', max_length=50),
        ),
    ]
