# Generated by Django 4.2.16 on 2025-02-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_clientsurvey_cc1_alter_clientsurvey_cc2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientSurvey',
        ),
    ]
