# Generated by Django 4.2.16 on 2025-02-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_clientsurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientSurvey',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Transactional',
        ),
    ]
