# Generated by Django 4.2.16 on 2025-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_position_service_customuser_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='service',
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.position'),
        ),
    ]
