# Generated by Django 4.2.16 on 2025-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_customuser_service_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.service'),
        ),
    ]
