# Generated by Django 4.2.16 on 2025-04-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_customuser_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='services',
        ),
    ]
