# Generated by Django 4.2.16 on 2025-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_customuser_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsurvey',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users', to='home.service'),
        ),
    ]
