# Generated by Django 4.2.16 on 2025-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_branch_unit_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super', 'Super'), ('Staff', 'Staff'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
