# Generated by Django 4.2.16 on 2025-04-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_customuser_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super', 'Super'), ('Unit', 'Unit'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
