# Generated by Django 4.2.16 on 2025-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Super', 'Super'), ('Unit', 'Unit'), ('Client', 'Client')], max_length=20, null=True),
        ),
    ]
