# Generated by Django 4.2.16 on 2025-05-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'COS'), ('JO', 'JO')], default='Permanent', max_length=20),
        ),
    ]
