# Generated by Django 4.2.16 on 2025-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_position_position_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position_status',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'COS'), ('JO', 'JO')], default='Permanent', max_length=20),
        ),
    ]
