# Generated by Django 4.2.16 on 2026-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_customuser_position_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qrcode_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
