# Generated by Django 4.2.16 on 2026-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_customuser_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
